Style/Documentation:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
# Metrics/AbcSize:
#   Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
Style/BlockComments:
  Description: 'Do not use block comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-block-comments'
  Enabled: false
