Style/Documentation:
  Enabled: false
Style/EmptyLiteral:
  Enabled: false
# Metrics/AbcSize:
#   Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Lint/AssignmentInCondition:
  Enabled: false
